# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=30),
        ),
    ]
