# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='eventdate',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
