# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_booking_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
